spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  grpc:
    server:
      port: 9090
      enable-reflection: true




