syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.tanle.practice_gRPC.grpc";
option java_outer_classname = "StockTradingProto";

message Empty{}

service StockTradingService {
  rpc getStockPrice(StockRequest) returns (StockResponse);
  rpc subscribeStockPrice(StockRequest) returns (stream StockResponse);
  rpc bulkPlaceOrder(stream StockOrder) returns (StockSummary);
}



message StockOrder {
  string order_id = 1;
  string stock_symbol = 2;
  int32 quantity = 3;
  double price = 4;
  string order_type = 5;// BUY or SELL
}
message StockSummary {
  int32 total_order = 1;
  double total_amount = 2;
  int32 success_count = 3;
}

message StockRequest {
  string stock_symbol = 1;
}
message StockResponse {
  string stock_symbol = 1;
  double price = 2;
  string timestamp = 3;
}